###
POST http://localhost:8080/api/v1/projects
Content-Type: application/json

{
  "name": "Kyou Bot",
  "description": "Python discord bot wrapped using disnake. Built for Kyou's Asobi Playground Discord Server.",
  "imageUrl": "https://media.discordapp.net/attachments/967356760690159667/983676601894043648/ServerIcon.png?ex=66278b39&is=66151639&hm=cad93c5084bad56049a2276742b75a58a31abb8800b6c7262c06d672c8e2c247&=&format=webp&quality=lossless&width=481&height=481",
  "tags": [
    "Python", "Disnake", "Discord Bot", "Kyou", "Asobi Playground"
  ],
  "projectUrl": "https://github.com/vianneynara/kyou-bot",
  "ownerId": 1
}

###
GET http://localhost:8080/api/v1/projects

###
GET http://localhost:8080/api/v1/projects/6

###
PUT http://localhost:8080/api/v1/projects/
Content-Type: application/json

{
  "name": "Kyou Bot",
  "description": "Python discord bot wrapped using disnake.",
  "imageUrl": "https://media.discordapp.net/attachments/967356760690159667/983676601894043648/ServerIcon.png?ex=66278b39&is=66151639&hm=cad93c5084bad56049a2276742b75a58a31abb8800b6c7262c06d672c8e2c247&=&format=webp&quality=lossless&width=481&height=481",
  "tags": [
    "Python",
    "Disnake",
    "Discord Bot"
  ],
  "projectUrl": "https://github.com/vianneynara/kyou-bot",
  "ownerId": 1
}

###
DELETE http://localhost:8080/api/v1/projects/6
